# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SQL-Builder
version:      0.03
version_from: lib/SQL/Builder.pm
installdirs:  site
requires:
    Data::Dumper:                  2.121
    Scalar::Util:                  1.14

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
