# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SQL-Builder
version:      0.02
version_from: lib/SQL/Builder.pm
installdirs:  site
requires:
    Clone:                         0.18

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
